minimum_prek_version: 0.4.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: ".*\\.tmpl"
      - id: check-json
      - id: check-yaml
        files: .*\.(yaml|yml)$
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
      - id: shellcheck
        exclude: "^.*\\.(zsh|tmpl)$"

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args:
          - --strict

  # - repo: https://github.com/betterleaks/betterleaks
  #   rev: v1.8.1
  - repo: local
    hooks:
      - id: betterleaks-mise
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Betterleaks
        entry: betterleaks git --pre-commit --redact --staged --verbose
        language: mise
        additional_dependencies:
          # renovate: datasource=github-releases depName=betterleaks/betterleaks
          - betterleaks@1.8.1
        pass_filenames: false

  - repo: local
    hooks:
      - id: psscriptanalyzer
        name: PSScriptAnalyzer
        description: |
          PSScriptAnalyzer is a static code checker for PowerShell modules and scripts
        files: '.*\.(ps1|ps1\.tmpl)$'
        language: mise
        additional_dependencies:
          - powershell@7
        entry: bin/Invoke-ScriptAnalyzer.ps1 -Path . -Recurse -EnableExit -ExcludeRule PSAvoidUsingInvokeExpression
        pass_filenames: false
