#!/usr/bin/env bash

set -euo pipefail

# Track encrypted data files
generated_data_files=()

if [ -f "${HOME}/.config/chezmoi/key.txt" ]; then
    while IFS= read -r -d '' file; do
        if [ -f "$file" ]; then

            filename=$(basename "$file")
            file_hash=$(sha256sum "$file" | cut -d " " -f 1)

            output_filename="$filename"
            output_filename="tmp${output_filename%.age}"
            output_file="${CHEZMOI_WORKING_TREE}/home/.chezmoidata/${output_filename}"

            generated_data_files+=("$output_file")

            if [ ! -f "$output_file" ] || ! grep -q "$file_hash" "$output_file"; then
                echo "source state changed, decrypting to .chezmoidata: $filename"
                {
                    echo "# Generated by chezmoi hook, do not edit manually"
                    echo "# encrypted-file: ${file}"
                    echo "# encrypted-hash: ${file_hash}"
                } > "$output_file"
                "$CHEZMOI_EXECUTABLE" decrypt  "$file" >> "$output_file"
            fi

        fi
    done < <(find "${CHEZMOI_WORKING_TREE}/home/.chezmoidata" -name ".*.yaml.age" -print0)
fi

# Cleanup stale files
while IFS= read -r -d '' file; do
    if [[ ! "${generated_data_files[*]}" == *"${file}"* ]]; then
        rm "$file"
    fi
done < <(find "${CHEZMOI_WORKING_TREE}/home/.chezmoidata" -name "tmp*" -print0)
