versions:
  kubectl: v1.27.3          # renovate: datasource=github-releases depName=kubernetes/kubectl
  kustomize: v5.1.1         # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
  helm: v3.13.0             # renovate: datasource=github-releases depName=helm/helm
  direnv: v2.32.3           # renovate: datasource=github-releases depName=direnv/direnv
  starship: v1.16.0         # renovate: datasource=github-releases depName=starship/starship
  fzf: "0.42.0"             # renovate: datasource=github-releases depName=junegunn/fzf
  fd: v8.7.0                # renovate: datasource=github-releases depName=sharkdp/fd
  backstage_go: v0.8.0      # renovate: datasource=github-releases depName=einride/backstage-go
  trivy: v0.45.1            # renovate: datasource=github-releases depName=aquasecurity/trivy
  age: v1.1.1               # renovate: datasource=github-releases depName=FiloSottile/age
  wsl2_ssh_pageant: v1.4.0  # renovate: datasource=github-releases depName=BlackReloaded/wsl2-ssh-pageant
  gitleaks: v8.18.0         # renovate: datasource=github-releases depName=gitleaks/gitleaks
  trufflehog: v3.57.0       # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
  eza: v0.13.1              # renovate: datasource=github-releases depName=eza-community/eza

pipx_packages:
  all:
    - pre-commit
    - yq

scoop_packages:
  all: []

winget_packages:
  all:
    - JernejSimoncic.Wget
    - Microsoft.WindowsTerminal
    - Microsoft.VisualStudioCode
    - eza-community.eza
  personal:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl
    - jqlang.jq
  work1:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl

kubectl_krew_plugins:
  - oidc-login
  - sudo
  - cert-manager
  - ingress-nginx
  - deprecations
  - outdated
  - get-all
  - starboard
  - resource-capacity
  - open-svc
  - popeye
  - explore
