versions:
  kubectl: v1.27.3          # renovate: datasource=github-releases depName=kubernetes/kubectl
  kustomize: v5.1.1         # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
  helm: v3.12.3             # renovate: datasource=github-releases depName=helm/helm
  direnv: v2.32.3           # renovate: datasource=github-releases depName=direnv/direnv
  starship: v1.16.0         # renovate: datasource=github-releases depName=starship/starship
  fzf: "0.42.0"             # renovate: datasource=github-releases depName=junegunn/fzf
  fd: v8.7.0                # renovate: datasource=github-releases depName=sharkdp/fd
  backstage_go: v0.8.0      # renovate: datasource=github-releases depName=einride/backstage-go
  trivy: v0.44.1            # renovate: datasource=github-releases depName=aquasecurity/trivy
  age: v1.1.1               # renovate: datasource=github-releases depName=FiloSottile/age

pipx_packages:
  all:
    - pre-commit
    - yq

scoop_packages:
  all: []

winget_packages:
  all:
    - JernejSimoncic.Wget
    - Microsoft.WindowsTerminal
    - jqlang.jq
  personal:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl
  work1:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl

kubectl_krew_plugins:
  - oidc-login
  - sudo
  - cert-manager
  - ingress-nginx
  - deprecations
  - outdated
  - get-all
  - starboard
  - resource-capacity
  - open-svc
  - popeye
  - explore
