versions:
  uv: "0.5.0"               # renovate: datasource=github-releases depName=astral-sh/uv
  kubectl: v1.27.3          # renovate: datasource=github-releases depName=kubernetes/kubectl
  kustomize: v5.5.0         # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
  helm: v3.16.2             # renovate: datasource=github-releases depName=helm/helm
  direnv: v2.35.0           # renovate: datasource=github-releases depName=direnv/direnv
  starship: v1.21.1         # renovate: datasource=github-releases depName=starship/starship
  fzf: v0.56.0              # renovate: datasource=github-releases depName=junegunn/fzf
  fd: v10.2.0               # renovate: datasource=github-releases depName=sharkdp/fd
  backstage_go: v0.9.0      # renovate: datasource=github-releases depName=einride/backstage-go
  trivy: v0.57.0            # renovate: datasource=github-releases depName=aquasecurity/trivy
  age: v1.2.0               # renovate: datasource=github-releases depName=FiloSottile/age
  wsl2_ssh_pageant: v1.4.0  # renovate: datasource=github-releases depName=BlackReloaded/wsl2-ssh-pageant
  gitleaks: v8.21.2         # renovate: datasource=github-releases depName=gitleaks/gitleaks
  trufflehog: v3.83.5       # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
  eza: v0.20.7             # renovate: datasource=github-releases depName=eza-community/eza
  bat: v0.24.0              # renovate: datasource=github-releases depName=sharkdp/bat
  dasel: v2.8.1             # renovate: datasource=github-releases depName=TomWright/dasel
  mise: v2024.11.4           # renovate: datasource=github-releases depName=jdx/mise
  multi_gitter: v0.53.1     # renovate: datasource=github-releases depName=lindell/multi-gitter
  gopass: v1.15.14          # renovate: datasource=github-releases depName=gopasspw/gopass

python_tools:
  all:
    - pre-commit
    - yq
    - ruff

scoop_packages:
  all: []

winget_packages:
  all:
    - JernejSimoncic.Wget
    - Microsoft.WindowsTerminal
    - Microsoft.VisualStudioCode
    - eza-community.eza
    - Git.Git
  personal:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl
    - jqlang.jq
  work1:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl
    - SlackTechnologies.Slack
    - Postman.Postman
    - GIMP.GIMP
    - MuhammedKalkan.OpenLens
    - dbeaver.dbeaver

kubectl_krew_plugins:
  - oidc-login
  - sudo
  - cert-manager
  # - ingress-nginx
  - deprecations
  - outdated
  - get-all
  - starboard
  - resource-capacity
  - open-svc
  - popeye
  - explore
  - view-quotas
