versions:
  pipx_installer: "1.5.0"   # renovate: datasource=github-releases depName=pypa/pipx
  kubectl: v1.27.3          # renovate: datasource=github-releases depName=kubernetes/kubectl
  kustomize: v5.4.2         # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
  helm: v3.15.1             # renovate: datasource=github-releases depName=helm/helm
  direnv: v2.34.0           # renovate: datasource=github-releases depName=direnv/direnv
  starship: v1.19.0         # renovate: datasource=github-releases depName=starship/starship
  fzf: "0.52.1"             # renovate: datasource=github-releases depName=junegunn/fzf
  fd: v10.1.0                # renovate: datasource=github-releases depName=sharkdp/fd
  backstage_go: v0.8.0      # renovate: datasource=github-releases depName=einride/backstage-go
  trivy: v0.52.0            # renovate: datasource=github-releases depName=aquasecurity/trivy
  age: v1.1.1               # renovate: datasource=github-releases depName=FiloSottile/age
  wsl2_ssh_pageant: v1.4.0  # renovate: datasource=github-releases depName=BlackReloaded/wsl2-ssh-pageant
  gitleaks: v8.18.3         # renovate: datasource=github-releases depName=gitleaks/gitleaks
  trufflehog: v3.77.0       # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
  eza: v0.18.16              # renovate: datasource=github-releases depName=eza-community/eza
  bat: v0.24.0              # renovate: datasource=github-releases depName=sharkdp/bat
  dasel: v2.7.0             # renovate: datasource=github-releases depName=TomWright/dasel
  mise: v2024.6.1          # renovate: datasource=github-releases depName=jdx/mise
  multi_gitter: v0.52.0     # renovate: datasource=github-releases depName=lindell/multi-gitter

pipx_packages:
  all:
    - pre-commit
    - yq
    - ruff

scoop_packages:
  all: []

winget_packages:
  all:
    - JernejSimoncic.Wget
    - Microsoft.WindowsTerminal
    - Microsoft.VisualStudioCode
    - eza-community.eza
  personal:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl
    - jqlang.jq
    - Foundry376.Mailspring
  work1:
    - Bitwarden.Bitwarden
    - Kubernetes.kubectl

kubectl_krew_plugins:
  - oidc-login
  - sudo
  - cert-manager
  - ingress-nginx
  - deprecations
  - outdated
  - get-all
  - starboard
  - resource-capacity
  - open-svc
  - popeye
  - explore
