versions:
  kustomize: v5.1.0         # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
  helm: v3.12.2             # renovate: datasource=github-releases depName=helm/helm
  direnv: v2.32.3           # renovate: datasource=github-releases depName=direnv/direnv
  starship: v1.15.0         # renovate: datasource=github-releases depName=starship/starship
  fzf: "0.42.0"             # renovate: datasource=github-releases depName=junegunn/fzf
  fd: v8.7.0                # renovate: datasource=github-releases depName=sharkdp/fd
  backstage_go: v0.8.0      # renovate: datasource=github-releases depName=einride/backstage-go
  trivy: v0.43.1            # renovate: datasource=github-releases depName=aquasecurity/trivy
  age: v1.1.1               # renovate: datasource=github-releases depName=FiloSottile/age
