name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linux-desktop:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - personal
          - work1
          - work2
        container:
          - ubuntu:latest
          - debian:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prerequisites
        run: apt-get update -q && apt-get install -y -q python3 python3-pip python3-venv curl git

      - name: Setup PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache Chezmoi external
        uses: actions/cache@v5
        with:
          path: "~/.cache/chezmoi/external"
          key: ${{ runner.os }}-${{ matrix.profile }}-${{ matrix.container }}-chezmoi-external

      - name: Decrypt age key
        env:
          CHEZMOI_KEY: ${{ secrets.CHEZMOI_KEY }}
        run: |
          mkdir -p ${HOME}/.config/chezmoi
          echo "$CHEZMOI_KEY" | base64 --decode > ${HOME}/.config/chezmoi/key.txt

      - name: Chezmoi init & apply
        env:
          DATA_profile: ${{ matrix.profile }}
          IS_DESKTOP: "true"
        run: |
          git config --global --add safe.directory $(pwd)
          ./install.sh

      - name: Assert
        run: |
          if ! grep -q "is_desktop: true" ${HOME}/.config/chezmoi/chezmoi.yaml; then
            echo "::error file=chezmoi.yaml::is_desktop: true not found"
            exit 1
          fi

      - name: Remove age key
        if: always()
        run: |
          rm ${HOME}/.config/chezmoi/key.txt


  linux-server:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - personal
          - work1
        container:
          - ubuntu:latest
          - debian:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prerequisites
        run: apt-get update -q && apt-get install -y -q python3 curl

      - name: Setup PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache Chezmoi external
        uses: actions/cache@v5
        with:
          path: "~/.cache/chezmoi/external"
          key: ${{ runner.os }}-${{ matrix.profile }}-${{ matrix.container }}-chezmoi-external

      - name: Chezmoi init & apply
        env:
          DATA_profile: ${{ matrix.profile }}
        run: |
          ./install.sh

      - name: Assert
        run: |
          if ! grep -q "is_server: true" ${HOME}/.config/chezmoi/chezmoi.yaml; then
            echo "::error file=chezmoi.yaml::is_server: true not found"
            exit 1
          fi

  linux-server-armv5:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Cache Chezmoi external
        uses: actions/cache@v5
        with:
          path: "~/.cache/chezmoi/external"
          key: ${{ runner.os }}-armv5-chezmoi-external

      - name: Run chezmoi test in armv5
        run: |
          docker run --rm \
            -v "$PWD:$PWD" \
            -v "$HOME:$HOME" \
            -w $PWD \
            arm32v5/debian \
            bash -c '
              set -euo pipefail

              apt-get update -q && apt-get install -y -q git gpg python3 curl

              export PATH="$HOME/bin:$PATH"
              export DATA_profile=personal

              git config --global --add safe.directory /work
              ./install.sh
              chezmoi managed

              if ! grep -q "is_server: true" "$HOME/.config/chezmoi/chezmoi.yaml"; then
                echo "is_server: true not found"
                exit 1
              fi
            '

      - name: Assert
        run: |
          if ! grep -q "is_server: true" ${HOME}/.config/chezmoi/chezmoi.yaml; then
            echo "::error file=chezmoi.yaml::is_server: true not found"
            exit 1
          fi