name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linux-desktop:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - personal
          - work1
          - work2
        container:
          - ubuntu:latest
          - debian:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prerequisites
        run: apt-get update -q && apt-get install -y -q python3 python3-pip python3-venv curl git

      - name: Setup PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache Chezmoi external
        uses: actions/cache@v5
        with:
          path: "~/.cache/chezmoi/external"
          key: ${{ runner.os }}-${{ matrix.profile }}-${{ matrix.container }}-chezmoi-external

      - name: Decrypt age key
        env:
          CHEZMOI_KEY: ${{ secrets.CHEZMOI_KEY }}
        run: |
          mkdir -p ${HOME}/.config/chezmoi
          echo "$CHEZMOI_KEY" | base64 --decode > ${HOME}/.config/chezmoi/key.txt

      - name: Chezmoi init & apply
        env:
          DATA_profile: ${{ matrix.profile }}
          IS_DESKTOP: "true"
        run: |
          git config --global --add safe.directory $(pwd)
          ./install.sh

      - name: Assert
        run: |
          if ! grep -q "is_desktop: true" ${HOME}/.config/chezmoi/chezmoi.yaml; then
            echo "::error file=chezmoi.yaml::is_desktop: true not found"
            exit 1
          fi

      - name: Remove age key
        if: always()
        run: |
          rm ${HOME}/.config/chezmoi/key.txt


  linux-server:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - personal
          - work1
        container:
          - ubuntu:latest
          - debian:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prerequisites
        run: apt-get update -q && apt-get install -y -q python3 python3-pip curl

      - name: Setup PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache Chezmoi external
        uses: actions/cache@v5
        with:
          path: "~/.cache/chezmoi/external"
          key: ${{ runner.os }}-${{ matrix.profile }}-${{ matrix.container }}-chezmoi-external

      - name: Chezmoi init & apply
        env:
          DATA_profile: ${{ matrix.profile }}
        run: |
          ./install.sh

      - name: Assert
        run: |
          if ! grep -q "is_server: true" ${HOME}/.config/chezmoi/chezmoi.yaml; then
            echo "::error file=chezmoi.yaml::is_server: true not found"
            exit 1
          fi

  linux-server-armv7:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - personal

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run ARM container
        env:
          DATA_profile: ${{ matrix.profile }}
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v $PWD:/workspace \
            -w /workspace \
            arm32v7/debian:bookworm \
            bash -c '
              set -e
              apt update
              apt install -y curl git

              curl -fsLS get.chezmoi.io -o install.sh
              sh install.sh -b /usr/local/bin -t v2.69.2

              echo "Running chezmoi"
              /usr/local/bin/chezmoi --version
              /usr/local/bin/chezmoi init --apply --verbose
              /usr/local/bin/chezmoi managed
              echo "Done running chezmoi"
            '

      #       mkdir -p results
      #       cp ${HOME}/.config/chezmoi/chezmoi.yaml results/chezmoi.yaml
      #       chmod -R a+r results
      # - name: Assert
      #   run: |
      #     if ! grep -q "is_server: true" results/chezmoi.yaml; then
      #       echo "::error file=chezmoi.yaml::is_server: true not found"
      #       exit 1
      #     fi

  windows-desktop:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - personal
        shell_test:
          - powershell
          - pwsh
          - pwsh-in-powershell
        include:
          - shell_test_: pwsh
            runner_shell: pwsh
            ps1_command: pwsh.exe
          - shell_test: pwsh-in-powershell
            runner_shell: powershell
            ps1_command: pwsh.exe
          - shell_test: powershell
            runner_shell: powershell
            ps1_command: powershell.exe

    runs-on: windows-2025
    defaults:
      run:
        shell: ${{ matrix.runner_shell }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prerequisites
        run: |
          winget install chezmoi --disable-interactivity --accept-source-agreements
          echo "$Env:LOCALAPPDATA\Microsoft\WinGet\Links" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Decrypt age key
        env:
          CHEZMOI_KEY: ${{ secrets.CHEZMOI_KEY }}
        shell: bash
        run: |
          mkdir -p ${HOME}/.config/chezmoi
          echo "$CHEZMOI_KEY" | base64 --decode > ${HOME}/.config/chezmoi/key.txt

      - name: Cache Chezmoi external
        uses: actions/cache@v5
        with:
          path: "~/.cache/chezmoi/external"
          key: ${{ runner.os }}-${{ matrix.profile }}-${{ matrix.runner_shell }}-chezmoi-external

      - name: Chezmoi init & apply
        uses: nick-fields/retry@v4
        env:
          DATA_profile: ${{ matrix.profile }}
          CHEZMOI_PS1_COMMAND: ${{ matrix.ps1_command }}
        with:
          timeout_minutes: 15
          max_attempts: 3
          shell: ${{ matrix.runner_shell }}
          command: |
            echo "Running chezmoi init --apply"
            chezmoi init --apply --source $Env:GITHUB_WORKSPACE

      - name: Remove age key
        if: always()
        shell: bash
        run: |
          rm ${HOME}/.config/chezmoi/key.txt
