name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
